# Generated by Django 5.0.2 on 2024-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_date_joined_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_number',
            field=models.CharField(default='', max_length=10, verbose_name='post_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='recipient_name',
            field=models.CharField(default='', max_length=30, verbose_name='recipient_name'),
        ),
    ]
