# Generated by Django 5.0.2 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_state_user_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='post_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='recipient_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='suburb'),
        ),
    ]
