# Generated by Django 5.0.2 on 2024-03-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
