# Generated by Django 5.0.2 on 2024-03-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abn',
            field=models.CharField(max_length=150, null=True, verbose_name='abn'),
        ),
        migrations.AddField(
            model_name='user',
            name='acn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='acn'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=150, null=True, verbose_name='company_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
