# Generated by Django 5.0.2 on 2024-03-21 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_abn_user_acn_user_company_name_user_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
