# Generated by Django 5.0.2 on 2024-04-09 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1234567, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='abn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='abn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='8 kingsborough way', max_length=150, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='ee_shopping', max_length=150, verbose_name='company_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='NSW', max_length=100, verbose_name='state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
