# Generated by Django 5.0.2 on 2024-04-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(default='NSW', max_length=150, verbose_name='address1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='position'),
        ),
    ]
