# Generated by Django 5.0.2 on 2024-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_address_user_address1_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='Manager', max_length=50, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='recipient_name',
            field=models.CharField(blank=True, default='Nelson', max_length=150, verbose_name='recipient_name'),
            preserve_default=False,
        ),
    ]
