# Generated by Django 5.0.2 on 2024-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_position_alter_user_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipient_name',
            field=models.CharField(max_length=150, verbose_name='recipient_name'),
        ),
    ]
