# Generated by Django 5.0.2 on 2024-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='sku'),
        ),
    ]
