# Generated by Django 5.0.2 on 2024-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_alter_production_sku_alter_productionitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='productions.production'),
        ),
    ]
