# Generated by Django 5.0.2 on 2024-04-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_production_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='class_grade',
            field=models.CharField(default='High Tensile Class 8.8', max_length=100, verbose_name='class_grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='description',
            field=models.TextField(default='welcome all', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='plating',
            field=models.CharField(default='1234', max_length=100, verbose_name='plating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='standard',
            field=models.CharField(default='AS1252:2016 K0', max_length=100, verbose_name='standard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='size',
            field=models.CharField(max_length=100, verbose_name='size'),
        ),
    ]
