# Generated by Django 5.0.2 on 2024-04-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_alter_production_class_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='highest_price',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='highest_price'),
        ),
        migrations.AlterField(
            model_name='production',
            name='lowest_price',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='lowest_price'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productions.production'),
        ),
    ]
