# Generated by Django 5.0.2 on 2024-04-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_alter_production_highest_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productions.production'),
        ),
    ]
