# Generated by Django 5.0.2 on 2024-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0007_alter_production_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='sku'),
        ),
    ]
