# Generated by Django 5.0.2 on 2024-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0008_alter_productionitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='category',
            field=models.CharField(default='Bolt', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='category',
            field=models.CharField(default='Bolt', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitem',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
    ]
