# Generated by Django 5.0.2 on 2024-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_production_category_production_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category'),
        ),
    ]
