# Generated by Django 5.0.2 on 2024-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0010_alter_productionitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='class_grade',
        ),
        migrations.RemoveField(
            model_name='production',
            name='description',
        ),
        migrations.RemoveField(
            model_name='production',
            name='plating',
        ),
        migrations.RemoveField(
            model_name='production',
            name='single_item',
        ),
        migrations.RemoveField(
            model_name='production',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='productionitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productionitem',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productionitem',
            name='size',
        ),
        migrations.AddField(
            model_name='production',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='images'),
        ),
    ]
