# Generated by Django 5.0.2 on 2024-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0011_remove_production_class_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='specification',
            field=models.JSONField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='specification',
            field=models.JSONField(blank=True, null=True, verbose_name='specification'),
        ),
    ]
