# Generated by Django 5.0.2 on 2024-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0012_alter_production_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='images'),
        ),
    ]
