# Generated by Django 5.0.2 on 2024-04-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0014_alter_production_status_alter_productionitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='sku',
            field=models.CharField(blank=True, max_length=7, unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='sku',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='sku'),
        ),
    ]
