# Generated by Django 5.0.2 on 2024-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0015_alter_production_sku_alter_productionitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='sku',
            field=models.CharField(max_length=7, unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='sku',
            field=models.CharField(max_length=12, unique=True, verbose_name='sku'),
        ),
    ]
