# Generated by Django 5.0.2 on 2024-03-21 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_price', models.FloatField(default=0, editable=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('post_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='post_number')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True, verbose_name='suburb')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='address')),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='recipient_name')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Confirmed'), (4, 'Shipped')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('sum_price', models.FloatField(default=0, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='productions.production')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
