# Generated by Django 5.0.2 on 2024-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Confirmed'), (4, 'Shipped'), (5, 'Closed')], default=1, verbose_name='Status'),
        ),
    ]
