# Generated by Django 5.0.2 on 2024-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='42 church ave', max_length=150, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='223344', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='Joy', max_length=150, verbose_name='recipient_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='NSW', max_length=100, verbose_name='state'),
            preserve_default=False,
        ),
    ]
