# Generated by Django 5.0.2 on 2024-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='net_total_price',
            field=models.FloatField(default=0, editable=False, verbose_name='net_total_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, editable=False, verbose_name='total_price'),
        ),
    ]
