# Generated by Django 5.0.2 on 2024-04-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_gst_order_net_total_price_alter_order_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='net_total_price',
            field=models.FloatField(default=0, verbose_name='net_total_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='total_price'),
        ),
    ]
