# Generated by Django 5.0.2 on 2024-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_gst_order_net_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='net_total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
