# Generated by Django 5.0.2 on 2024-04-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_net_total_price_alter_order_total_price'),
        ('productions', '0016_alter_production_sku_alter_productionitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='productions.productionitem'),
        ),
    ]
